### ISSUE TITLE
BA package broken - ask for review

### ISSUE THREAD

**Issue by noraj** [bannsec/stegoVeritas#21]
Hi @bannsec, can you tell me if the solutions discussed [here](https://github.com/BlackArch/blackarch/issues/2564#issuecomment-565630081) seem correct to you?

The goal is to fix the BA package of stegoveritas that is actually broken.

**Comment by bannsec** [comment]
yeah, so basically I had to add my own quasi-versions of python-pfp due to their broken dependencies at the time. It appears they've been updating again now so maybe can switch back to the original python-pfp, but have not tested that.

distro was used to help with cross platform distribution identification.

binwalk's last official release in pypy was 2015. Tried to get them to push a new update but no-go, so basically pushed my own deployment of it. You're correct that it should be fine to use the binwalk from the system if it's already present.
